package org.hisp.dhis.util;

import java.net.URI;
import java.net.URISyntaxException;
import java.util.Base64;

import org.apache.http.HttpHeaders;
import org.apache.http.client.methods.HttpRequestBase;
import org.apache.http.client.utils.URIBuilder;
import org.hisp.dhis.Dhis2Config;

public class HttpUtils
{
    /**
     * Returns a basic authentication string which is generated by prepending
     * "Basic " and Base64-encoding username:password.
     *
     * @param config the {@link Dhis2Config}.
     * @return the encoded string.
     */
    public static String getBasicAuthString( Dhis2Config config )
    {
        String value = config.getUsername() + ":" + config.getPassword();

        return "Basic " + Base64.getEncoder().encodeToString( value.getBytes() );
    }

    /**
     * Adds basic authentication to the given request using the Authorization header.
     *
     * @param request the {@link HttpRequestBase}.
     * @param config the {@link Dhis2Config}.
     * @param <T> class.
     * @return the request.
     */
    public static <T extends HttpRequestBase> T withBasicAuth( T request, Dhis2Config config )
    {
        request.setHeader( HttpHeaders.AUTHORIZATION, getBasicAuthString( config ) );
        return request;
    }

    /**
     * Builds on URI without throwing checked exceptions.
     *
     * @param uriBuilder the {@link URIBuilder}.
     * @return a {@link URI}.
     */
    public static URI build( URIBuilder uriBuilder )
    {
        try
        {
            return uriBuilder.build();
        }
        catch ( URISyntaxException ex )
        {
            throw new RuntimeException( ex );
        }
    }
}
