name: Merge to Main

on:
  push:
    branches:
      - 'master'

jobs:
  unit-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: 17
          distribution: temurin
      - name: Test
        run: mvn clean install --update-snapshots -q

  artifact:
    name: Publish - Nexus
    runs-on: ubuntu-latest
    needs: unit-test
    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: 17
          distribution: temurin

      - name: Remove snapshot
        run: mvn -B versions:set -DremoveSnapshot -DgenerateBackupPoms=false

      - name: Release Maven package
        env:
          SONATYPE_PORTAL_USERNAME: ${{ secrets.SONATYPE_PORTAL_USERNAME }}
          SONATYPE_PORTAL_PASSWORD: ${{ secrets.SONATYPE_PORTAL_PASSWORD }}
          GPG_PASSPHRASE: ${{ secrets.PGP_PASSPHRASE }}
          GPG_SECRET_KEYS: ${{ secrets.PGP_PRIVATE_KEY }}
        run: |
          echo -e "$GPG_SECRET_KEYS" | gpg --import --no-tty --batch --yes
          mvn clean deploy --settings .mvn/settings.xml -Dgpg.skip=false -Dmaven.test.skip=true -B
